### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by aymenitc** [Keivan-sf/chart-sc#1]
probably, tradingView changed website design.

`[ERROR] Error: Evaluation failed: TypeError: Cannot read property 'click' of null`

**Comment by Keivan-sf** [comment]
Hi, Thanks for reporting. Sorry for the clumsy code you've faced. This package is kinda old. but I'll take a look at this right now.
just two questions to be sure of your issue:
Are you using dark mode? 
And do you have the same problem while using the light mode?

**Comment by aymenitc** [comment]
Thank you,
I was using the light mode, but I tried dark mode too and get the same error.
It was working for me before, and I actually changed screenshot file type to jpeg to be able to send it via Whatsapp. and it was working until few days.

Thank you again.

**Comment by Keivan-sf** [comment]
I have done a hot fix to `1.0.4`  until I write a proper scrapping structure.

Please follow the steps below in order to fix the issues you're facing.

- Install the package via npm (or make a clone of github repo)
```bash
npm i chart-sc@latest
```

- Then for the puppeteer to work properly you need to install chromium manually:

> Bear in mind that your app might not need this step, So I recommend you check and run your app first and see if you would face any error related to `chromium` or not.
```
node node_modules/puppeteer-core/install.js
```

> Be aware that the path to `./puppeteer-core/install.js` can be different if you're using any other package manager rather than **npm**. In that case, Just open the `node_modules` folder and look for `puppeteer-core` folder path and replace it with the path shown in the script above.

this might take a little while but it's one-time only

If you've faced `PUPPETEER_SKIP_DOWNLOAD` problem , just open `node_modules/puppeteer-core/` (which can be different with different package managers) and use the script below:
```bash
# in Windows
set PUPPETEER_SKIP_DOWNLOAD=

# in macOS/Linux
export PUPPETEER_SKIP_DOWNLOAD=
```

And just try the second step again. You should be good to go

**Note:** First requests might take a little while but others would find their acceptable speed due to puppeteer caching being enabled.

I'm sorry if it was too long too read. I hope it won't be a `TL;DR` thing.
Please share the results if you found the time to give this a chance

**Comment by aymenitc** [comment]
excellent 😊
Working now 👍
Thank you very much 💓

**Comment by Keivan-sf** [comment]
Happy that it's working now :+1: 
And thanks for reporting again

I'll close the issue
